//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIACinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSession
    {
        public int Id { get; set; }
        public double Price { get; set; }
        public System.DateTime SessionDate { get; set; }
        public int MovieId { get; set; }
        public int StageId { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
