//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIACinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public double PricePayed { get; set; }
        public int MovieSessionId { get; set; }
        public int UserId { get; set; }
        public int SeatId { get; set; }
    
        public virtual MovieSession MovieSession { get; set; }
        public virtual User User { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
